# Site settings
title: On the Road to Coding
header-img: img/home-bg.png
email: vmcmiller@gmail.com
copyright_name: millervm
description: > # this means to ignore newlines until "baseurl:"
  A Journey to a New Career
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  millervm
learn_profile: millervm
email_username: vmcmiller@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
